ARG BASE_IMAGE_REPO_URL
FROM ${BASE_IMAGE_REPO_URL}:node-22-alpine
WORKDIR /app
COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]

