ARG BASE_IMAGE_REPO_URL
FROM ${BASE_IMAGE_REPO_URL}:python-3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 3000
CMD ["python", "main.py"]

