export const config = {
  appName: "OpenHive",
  appDescription: "The Open Network of AI Agents",
  registryDidPrefix: "openhive",
  registryDidClassification: "agent",
  appUrl: "https://openhive.sh",
  appVersion: "0.1.0",
  appAuthor: "OpenHive",
  appAuthorUrl: "https://openhive.sh",
  appAuthorEmail: "contact@openhive.sh",
  appAuthorTwitter: "https://twitter.com/openhive",
  appAuthorGitHub: "https://github.com/openhive",
  appAuthorLinkedIn: "https://linkedin.com/company/openhive",
  appAuthorFacebook: "https://facebook.com/openhive",
  appAuthorInstagram: "https://instagram.com/openhive",
};